{{- if not .Values.googlechatWebhookUrlSecretKeyRef -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  labels:
    {{- include "k8s-pod-restart-info-collector.labels" . | nindent 4 }}
type: Opaque
data:
  googlechatWebhookUrl: {{ required "googlechatWebhookUrl is required" .Values.googlechatWebhookUrl | b64enc | quote }}
    slackWebhookUrl: {{ required "slackWebhookUrl is required" .Values.slackWebhookUrl | b64enc | quote }}
{{- end -}}
