# Default values for k8s-pod-restart-info-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# clusterName: "Change-Me"
# slackWebhookUrl: "https://hooks.slack.com/services/Change-Me"
# slackWebhookUrlSecretKeyRef:
#   key: "slackWebhookUrl"
#   name: "k8s-pod-restart-info-collector"
slackChannel: "restart-info-nonprod"
slackUsername: "k8s-pod-restart-info-collector"
muteSeconds: 600
ignoreRestartCount: 30
# googlechatWebhookUrl: "https://chat.googleapis.com/v1/spaces/SPACE_ID/messages?key=KEY&token=TOKEN"
# googlechatWebhookUrlSecretKeyRef:
#   key: "googlechatWebhookUrl"
#   name: "k8s-pod-restart-info-collector"
useGooglechat: true

  
# A set of namespaces to be ignored. This should be provided as a comma-separated list or a regular expression.
ignoredNamespaces: ""
# A set of pod name prefixes to be ignored. This should be provided as a comma-separated list or a regular expression.
ignoredPodNamePrefixes: ""

# A set of namespaces to be watched. This should be provided as a comma-separated list or a regular expression.
watchedNamespaces: ""
# A set of pod name prefixes to be watched. This should be provided as a comma-separated list or a regular expression.
watchedPodNamePrefixes: ""

# Whether restart events with an exit code of 0 should be ignored, true or false
ignoreRestartsWithExitCodeZero: false

image:
  repository: 107126629234.dkr.ecr.ap-southeast-1.amazonaws.com/k8s-pod-restart-info-collector
  tag: "ab5d3383-1713423536"

resources: 
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 50Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
